### ISSUE TITLE
Start with FF 56.0.2 (debian jessie)

### ISSUE THREAD

**Issue by amtx** [mollat/pull-amazon-orders-to-csv#1]
An empty FF Window opens - then after a while in the console I get:
pull-amazon-orders-to-csv# ./pull-orders.sh 2016
 /usr/lib/ruby/2.1.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /usr/lib/ruby/2.1.0/net/protocol.rb:152:in `rbuf_fill'
	from /usr/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
	from /usr/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
	from /usr/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
	from /usr/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
	from /usr/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
	from /usr/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
	from /usr/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
	from /usr/lib/ruby/2.1.0/net/http.rb:1378:in `request'
	from /usr/lib/ruby/2.1.0/net/http.rb:1371:in `block in request'
	from /usr/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /usr/lib/ruby/2.1.0/net/http.rb:1369:in `request'
	from /var/lib/gems/2.1.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
	from /var/lib/gems/2.1.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
	from /var/lib/gems/2.1.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
	from /var/lib/gems/2.1.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from /var/lib/gems/2.1.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
	from /var/lib/gems/2.1.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/firefox/marionette/driver.rb:50:in `initialize'
	from /var/lib/gems/2.1.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/firefox/driver.rb:31:in `new'
	from /var/lib/gems/2.1.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/firefox/driver.rb:31:in `new'
	from /var/lib/gems/2.1.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/common/driver.rb:52:in `for'
	from /var/lib/gems/2.1.0/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver.rb:86:in `for'
	from pull-orders.rb:32:in `&lt;main&gt;'

sysinfo:
DebianVersion: 8.11
Boot options:
BOOT_IMAGE=/boot/vmlinuz-3.16.0-4-amd64 root=/dev/md1 ro quiet
Kernel: 3.16.0-4-amd64
System is 64 bit

**Comment by mollat** [comment]
I would recommend to update the ruby version before looking further into this, as your ruby version is now almost 5 years old. Please report if it works with a newer version.
