### ISSUE TITLE
Script won't start. Can't load rubygems.rb

### ISSUE THREAD

**Issue by Remonell** [mollat/pull-amazon-orders-to-csv#3]
Hey there,
trying to get your script to work. Installed ruby + selenium, but I get following error message when I try to run pull-orders.sh
[http://prntscr.com/k931ux](url)

Do you have any idea why that is? I tried to fix it for a couple of hours but I am no Linux pro :/

Kind regards

**Comment by mollat** [comment]
What is your Linux distribution? What is the output if you type in 'gem' into the console? If it is Debian/Ubuntu try 'apt install ruby-full' or look at

https://www.ruby-lang.org/en/documentation/installation/

**Comment by Remonell** [comment]
I am running Ubuntu x64. Is that detailed enough? Installing ruby-full did not help. The output of 'gem' is the same output when I try to run your script. 

<internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'

That is an interesting behaviour. I am doing more research and try to fix 'gem' first. That will probably make your script run too. I am thankful for any advice on how to fix this. 

Kind regards.

**Comment by mollat** [comment]
I think this issue is more ruby related, closing.
